# Generated by Django 5.2.17 on 2026-09-21 04:46

import django.db.models.deletion
import django.utils.timezone
import labops.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labops', '0003_laborder_sample_sampleevent_testcatalog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxevent',
            name='aggregate_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='lease_token',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='transport',
            field=models.CharField(default='local', max_length=16),
        ),
        migrations.CreateModel(
            name='FailedDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('consumer_name', models.CharField(max_length=64)),
                ('delivery_key', models.CharField(max_length=255)),
                ('envelope', models.JSONField(default=dict)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='RETRY', max_length=16)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True)),
                ('dlq_published_at', models.DateTimeField(null=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('resolution_note', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='labops_fail_status_58db1e_idx')],
                'constraints': [models.UniqueConstraint(fields=('consumer_name', 'delivery_key'), name='consumer_delivery_unique')],
            },
        ),
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('consumer_name', models.CharField(max_length=64)),
                ('event_id', models.UUIDField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('consumer_name', 'event_id'), name='consumer_event_unique')],
            },
        ),
        migrations.CreateModel(
            name='InventoryProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', labops.fields.Fixed6Field(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labops.batch')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labops.warehouse')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'warehouse'), name='projection_balance_unique')],
            },
        ),
    ]
