# Generated by Django 5.2.17 on 2026-09-28 01:17

import django.db.models.deletion
import django.utils.timezone
import uuid
import hashlib
import json
import math
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


INVENTORY_TYPES = [f'inventory.{kind}.posted' for kind in (
    'opening', 'receipt', 'issue', 'transfer', 'adjustment', 'reversal')]


def audit_and_backfill(apps, schema_editor):
    """Freeze writers before running. Never delete, merge or renumber legacy events."""
    alias = schema_editor.connection.alias
    Outbox = apps.get_model('labops', 'OutboxEvent')
    Processed = apps.get_model('labops', 'ProcessedEvent')
    Failed = apps.get_model('labops', 'FailedDelivery')
    Audit = apps.get_model('labops', 'DeliveryAudit')
    inventory = Outbox.objects.using(alias).filter(
        aggregate_type='stockmovement', event_type__in=INVENTORY_TYPES)
    duplicate_groups = list(inventory.values('aggregate_type', 'aggregate_id', 'aggregate_version')
                            .annotate(total=models.Count('id')).filter(total__gt=1)[:25])
    if duplicate_groups:
        # Failure rolls the migration back without touching retained rows. The
        # operator must audit the report and resolve through an approved repair.
        raise RuntimeError('Inventory aggregate/version data audit failed; migration is unsafe. '
                           'Historical rows were preserved. First 25 collisions: '
                           + json.dumps(duplicate_groups, default=str, sort_keys=True))
    counts = {'inventory_outboxes_hashed': 0, 'processed_rows_hashed': 0,
              'failed_deliveries_hashed': 0, 'unhashable_failed_rows': 0,
              'unhashable_inventory_rows': 0, 'duplicate_groups': 0}

    def checksum(value):
        # Frozen canonicalization: whole-envelope UTF-8 JSON, sorted keys, compact
        # separators, including trace carriers and JSONB-stable numeric identity.
        # Do not import evolving app code.
        def normalize(item):
            if type(item) is float and math.isfinite(item):
                number = Decimal(str(item))
                return int(number) if number == number.to_integral_value() else item
            if type(item) is dict:
                return {key: normalize(child) for key, child in item.items()}
            if type(item) is list:
                return [normalize(child) for child in item]
            return item
        return hashlib.sha256(json.dumps(normalize(value), sort_keys=True, separators=(',', ':'),
                                         ensure_ascii=False, allow_nan=False).encode('utf-8')).hexdigest()

    for row in inventory.iterator(chunk_size=1000):
        retained_envelope = {'event_id': str(row.id), 'event_type': row.event_type,
            'aggregate_type': row.aggregate_type, 'aggregate_id': str(row.aggregate_id),
            'aggregate_version': row.aggregate_version, 'schema_version': row.schema_version,
            'occurred_at': row.created_at.isoformat(),
            'trace_context': row.payload_json.get('_trace_context', {}) if isinstance(row.payload_json, dict) else {},
            'payload': row.payload_json}
        try:
            digest = checksum(retained_envelope)
        except (TypeError, ValueError, UnicodeError, RecursionError):
            counts['unhashable_inventory_rows'] += 1
            continue
        Outbox.objects.using(alias).filter(pk=row.pk).update(payload_hash=digest)
        counts['inventory_outboxes_hashed'] += 1
        counts['processed_rows_hashed'] += Processed.objects.using(alias).filter(
            event_id=row.id, payload_hash__isnull=True).update(payload_hash=digest)
    for row in Failed.objects.using(alias).all().iterator(chunk_size=1000):
        try:
            digest = checksum(row.envelope)
        except (TypeError, ValueError, UnicodeError, RecursionError):
            counts['unhashable_failed_rows'] += 1
            continue
        Failed.objects.using(alias).filter(pk=row.pk).update(original_hash=digest)
        counts['failed_deliveries_hashed'] += 1
    counts['legacy_processed_rows_without_evidence'] = Processed.objects.using(alias).filter(payload_hash__isnull=True).count()
    Audit.objects.using(alias).create(actor_label='migration:0005_event_contracts',
        action='SCHEMA_BACKFILL', outcome='SUCCEEDED',
        reason='Historical inventory identities audited before uniqueness; retained content hashed without mutation. '
               'Nullable hashes identify legacy rows without retained evidence; schema validity must be checked at runtime.',
        before_json={'contract_version': 4}, after_json=counts,
        authorization_json={'source': 'schema_migration', 'writer_freeze_required': True})


def enforce_append_only(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return  # SQLite demonstration uses application guards, not production DML guarantees.
    schema_editor.execute("""
        CREATE FUNCTION labops_deliveryaudit_append_only() RETURNS trigger
        LANGUAGE plpgsql AS $$ BEGIN
            RAISE EXCEPTION 'DeliveryAudit is append-only' USING ERRCODE = '55000';
        END $$
    """)
    schema_editor.execute("""
        CREATE TRIGGER labops_deliveryaudit_no_mutation
        BEFORE UPDATE OR DELETE ON labops_deliveryaudit
        FOR EACH ROW EXECUTE FUNCTION labops_deliveryaudit_append_only()
    """)


def remove_append_only(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('DROP TRIGGER IF EXISTS labops_deliveryaudit_no_mutation ON labops_deliveryaudit')
        schema_editor.execute('DROP FUNCTION IF EXISTS labops_deliveryaudit_append_only()')


class Migration(migrations.Migration):

    dependencies = [
        ('labops', '0004_reliable_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_label', models.CharField(blank=True, max_length=160)),
                ('action', models.CharField(max_length=64)),
                ('outcome', models.CharField(max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('original_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('authorization_json', models.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='faileddelivery',
            name='consumer_delivery_unique',
        ),
        migrations.AlterField(
            model_name='faileddelivery',
            name='delivery_key',
            field=models.CharField(max_length=600),
        ),
        migrations.AddField(
            model_name='faileddelivery',
            name='dlq_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faileddelivery',
            name='dlq_lease_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faileddelivery',
            name='dlq_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faileddelivery',
            name='dlq_next_attempt_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='faileddelivery',
            name='failure_class',
            field=models.CharField(default='transient', max_length=32),
        ),
        migrations.AddField(
            model_name='faileddelivery',
            name='lease_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faileddelivery',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faileddelivery',
            name='original_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='faileddelivery',
            name='source_cluster',
            field=models.CharField(blank=True, default='legacy', max_length=128),
        ),
        migrations.AddField(
            model_name='faileddelivery',
            name='source_generation',
            field=models.CharField(blank=True, default='legacy', max_length=128),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='payload_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='processedevent',
            name='payload_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='faileddelivery',
            index=models.Index(fields=['status', 'dlq_published_at', 'dlq_next_attempt_at'], name='delivery_dlq_due_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['transport', 'status', 'next_attempt_at'], name='outbox_route_due_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['aggregate_type', 'aggregate_id', 'aggregate_version'], name='outbox_aggregate_version_idx'),
        ),
        migrations.AddConstraint(
            model_name='faileddelivery',
            constraint=models.UniqueConstraint(fields=('consumer_name', 'source_cluster', 'source_generation', 'delivery_key'), name='consumer_source_delivery_unique'),
        ),
        migrations.AddField(
            model_name='deliveryaudit',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_audit_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryaudit',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='labops.faileddelivery'),
        ),
        migrations.AddField(
            model_name='deliveryaudit',
            name='outbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_audit_entries', to='labops.outboxevent'),
        ),
        migrations.AddIndex(
            model_name='deliveryaudit',
            index=models.Index(fields=['delivery', 'created_at'], name='delivery_audit_time_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryaudit',
            index=models.Index(fields=['outbox', 'created_at'], name='outbox_audit_time_idx'),
        ),
        migrations.RunPython(audit_and_backfill, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.UniqueConstraint(condition=models.Q(('aggregate_type', 'stockmovement'), ('event_type__in', INVENTORY_TYPES)), fields=('aggregate_type', 'aggregate_id', 'aggregate_version'), name='inventory_aggregate_version_uniq'),
        ),
        migrations.RunPython(enforce_append_only, remove_append_only),
    ]
